[package]
name = "cita-bft"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
dotenv = "0.10.0"
threadpool = "1.7.0"
serde = "1.0"
serde_derive = "1.0"
bincode = "0.8.0"
libproto = { git = "https://github.com/cryptape/cita-common.git", rev = "9a8a2978" }
util = { git = "https://github.com/cryptape/cita-common.git", rev = "9a8a2978" }
rustc-serialize = "0.3"
clap = "2"
pubsub = { git = "https://github.com/cryptape/cita-common.git", rev = "9a8a2978" }
cita-types = { git = "https://github.com/cryptape/cita-common.git", rev = "9a8a2978" }
cita-crypto = { git = "https://github.com/cryptape/cita-common.git", rev = "9a8a2978" }
proof = { git = "https://github.com/cryptape/cita-common.git", rev = "9a8a2978" }
time = "0.1.36"
engine = { git = "https://github.com/cryptape/cita-common.git", rev = "9a8a2978" }
lru-cache = "0.1"
logger = { git = "https://github.com/cryptape/cita-common.git", rev = "9a8a2978" }
authority_manage = { git = "https://github.com/cryptape/cita-common.git", rev = "9a8a2978" }
rustc-hex = "1.0"
crossbeam = "0.7"
bft-rs = { git = "https://github.com/cryptape/bft-rs.git", branch = "develop" }  #commitId=f8d526339d11a722a9b4f09db618d8deb45ace8d

[build-dependencies]
util = { git = "https://github.com/cryptape/cita-common.git", rev = "9a8a2978"}


[features]
default = ["secp256k1", "sha3hash", "rabbitmq", "verify_req"]
secp256k1 = ["cita-crypto/secp256k1", "libproto/secp256k1", "proof/secp256k1","engine/secp256k1"]
ed25519 = ["cita-crypto/ed25519", "libproto/ed25519", "proof/ed25519", "engine/ed25519"]
sm2 = ["cita-crypto/sm2", "libproto/sm2", "proof/sm2", "engine/sm2"]
sha3hash = ["util/sha3hash", "libproto/sha3hash", "proof/sha3hash", "engine/sha3hash"]
blake2bhash = ["util/blake2bhash", "libproto/blake2bhash", "proof/blake2bhash", "engine/blake2bhash"]
sm3hash = ["util/sm3hash", "libproto/sm3hash", "proof/sm3hash", "engine/sm3hash"]
rabbitmq = ["pubsub/rabbitmq"]
zeromq = ["pubsub/zeromq"]
kafka = ["pubsub/kafka"]
verify_req = ["bft-rs/verify_req"]